apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Mini-Docker PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: minidocker
    user: minidocker
    password: minidocker123
    editable: true
    jsonData:
      postgresVersion: 1500
      timescaleDB: false
